import type { Experience, Profile, Project, SkillGroup } from "./types";

export const seedProfile: Profile = {
  id: "seed-profile",
  name: "Josua Pane",
  title: "Sales & Data Analyst",
  bio: "Analyst experienced in large-scale retail data, reporting automation, sales operations, and dashboard development. I turn complex datasets into clear business insights with Python, SQL, Power BI, Tableau, and Excel.",
  location: "Jakarta, Indonesia",
  email: "panejwork@gmail.com",
  phone: "+62 813-4633-3059",
  linkedin_url: "https://linkedin.com/in/josuapane/",
  github_url: "https://github.com/josuapane13",
  cv_url: null,
  avatar_url: "/assets/avatar.jpg",
};

export const seedExperiences: Experience[] = [
  {
    id: "exp-1",
    category: "work",
    title: "Sales General Trade Analyst",
    organization: "Charoen Pokphand Food",
    location: "Jakarta, Indonesia (On-site)",
    period_start: "April 2026",
    period_end: "Present",
    description: null,
    highlights: [
      "Supervise development of the company's sales automation platform, translating business needs into a prioritized development roadmap.",
      "Own the rollout experience as liaison between 30+ distributors and the system vendor, resolving adoption pain points.",
      "Deliver Power BI sales analytics across 5,000+ outlets, saving 12 reporting hours per week.",
      "Conducted GPS-targeted market research that contributed to a 35% increase in new partner outlets.",
      "Built an internal tool that standardizes branch sales data and reduces administrative processing time by hours.",
    ],
    sort_order: 1,
  },
  {
    id: "exp-2",
    category: "work",
    title: "Data & Information Staff",
    organization: "Ministry of Transmigration",
    location: "Jakarta, Indonesia (On-site)",
    period_start: "November 2025",
    period_end: "April 2026",
    description: null,
    highlights: [
      "Coordinated and analyzed operational data across 16 national projects to support management decisions and planning.",
      "Built AI reporting workflows with n8n that reduced manual reporting time from days to hours.",
      "Presented structured reports and analytical insights to stakeholders.",
    ],
    sort_order: 2,
  },
  {
    id: "exp-3",
    category: "work",
    title: "Data Quality Checks & Business Analyst Trainee",
    organization: "GOVOKASI Indonesia",
    location: "Jakarta, Indonesia (Hybrid)",
    period_start: "November 2025",
    period_end: "April 2026",
    description: null,
    highlights: [
      "Validated more than 80,000 retail sales records to ensure accurate business reporting.",
      "Analyzed CRM and pipeline data for 30 active leads each week and produced monthly and quarterly Excel reports.",
    ],
    sort_order: 3,
  },
  {
    id: "exp-edu",
    category: "education",
    title: "Bachelor of Informatics",
    organization: "Telkom University",
    location: "Bandung, Indonesia",
    period_start: null,
    period_end: null,
    description: "GPA: 3.58/4.00",
    highlights: ["Machine Learning", "Data Visualization", "Project Management", "Entrepreneurship"],
    sort_order: 1,
  },
  {
    id: "exp-lead-1",
    category: "leadership",
    title: "Student Activities",
    organization: "Telkom University",
    location: "Bandung, Indonesia",
    period_start: null,
    period_end: null,
    description: "Participated in the Informatics Student Council, CCI Laboratory, and English Debate Club.",
    highlights: [],
    sort_order: 1,
  },
  {
    id: "exp-cert-1",
    category: "certification",
    title: "Procurement Manager Professional Certification",
    organization: "MTF Institute",
    location: null,
    period_start: null,
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 1,
  },
  {
    id: "exp-cert-2",
    category: "certification",
    title: "Data Analysis: Fullstack Intensive Bootcamp",
    organization: "MySkill",
    location: null,
    period_start: null,
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 2,
  },
  {
    id: "exp-cert-3",
    category: "certification",
    title: "Machine Learning 2024 Batch 1",
    organization: "Bangkit Academy",
    location: null,
    period_start: "2024",
    period_end: null,
    description: null,
    highlights: [],
    sort_order: 3,
  },
  {
    id: "exp-pub-1",
    category: "publication",
    title: "Natural Language Processing Research",
    organization: "8th International Conference on Data Science and Its Applications (ICoDSA)",
    location: null,
    period_start: null,
    period_end: null,
    description: "Final thesis research presented at the 8th ICoDSA Data Science Conference.",
    highlights: [],
    sort_order: 1,
  },
];

const group = (id: string, name: string, names: string[], sortOrder: number): SkillGroup => ({
  id,
  name,
  icon: null,
  sort_order: sortOrder,
  skills: names.map((name, index) => ({
    id: `${id}-${index + 1}`,
    group_id: id,
    name,
    sort_order: index + 1,
  })),
});

export const seedSkillGroups: SkillGroup[] = [
  group("sg-1", "Data Analysis", ["Python", "SQL", "Data Cleaning", "Statistical Analysis", "Predictive Analysis", "Process Improvement"], 1),
  group("sg-2", "Business & Sales", ["CRM Analysis", "Business Reporting", "Sales Operations", "ERP (SAP)", "Market Research"], 2),
  group("sg-3", "Visualization & Reporting", ["Power BI", "Tableau", "Microsoft Excel", "Pivot Tables", "XLOOKUP", "VBA"], 3),
  group("sg-4", "Automation & Tools", ["n8n", "Zapier", "Jira", "PHP", "Data Pipelines"], 4),
  group("sg-5", "Languages", ["Indonesian (Native)", "English (C2)", "German (A1)"], 5),
];

export const seedProjects: Project[] = [
  {
    id: "proj-1",
    title: "Sales Performance Analytics",
    subtitle: "Charoen Pokphand Food | Power BI",
    description: "Developed selling-in and selling-out, revenue, and customer-tier reporting across more than 5,000 outlets. The dashboards replaced repetitive reporting work and save approximately 12 hours each week.",
    tags: ["Power BI", "Sales Analytics", "Retail Data", "Business Reporting"],
    year: "2026",
    project_url: null,
    doc_url: "/assets/sales-performance-analyst_compressed.pdf",
    image_url: null,
    featured: true,
    sort_order: 1,
  },
  {
    id: "proj-2",
    title: "GPS-Targeted Outlet Research",
    subtitle: "Charoen Pokphand Food | Market Intelligence",
    description: "Created crawled, GPS-targeted lead lists to focus partner acquisition on high-potential areas. The resulting market research contributed to a 35% increase in new partner outlets.",
    tags: ["Python", "Web Crawling", "Market Research", "Geospatial Data"],
    year: "2026",
    project_url: null,
    doc_url: "/assets/gps-targeted-outlet-research.pdf",
    image_url: null,
    featured: true,
    sort_order: 2,
  },
  {
    id: "proj-3",
    title: "AI Reporting Automation",
    subtitle: "Ministry of Transmigration | n8n",
    description: "Built automated reporting workflows for operational data spanning 16 national projects, reducing a multi-day manual process to a matter of hours.",
    tags: ["n8n", "Workflow Automation", "Operational Data", "Reporting"],
    year: "2026",
    project_url: null,
    doc_url: null,
    image_url: "/assets/n8n-workflow.jpg",
    featured: true,
    sort_order: 3,
  },
  {
    id: "proj-4",
    title: "FitFoody Nutrition Tracking App",
    subtitle: "Bangkit Academy | Computer Vision",
    description: "Built an Android nutrition-tracking application for Indonesian cuisine. Processed scraped food datasets and analyzed more than 10,000 records to improve data quality for food classification and nutrition-analysis models.",
    tags: ["Computer Vision", "Machine Learning", "Data Processing", "Android"],
    year: "2024",
    project_url: null,
    doc_url: "/assets/fitfoody.pdf",
    image_url: null,
    featured: true,
    sort_order: 4,
  },
];
